apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-cluster-role-devops
rules:
  - apiGroups: [""]
    resources:
      [
        "configmaps",
        "endpoints",
        "secrets",
        "nodes",
        "pods",
        "services",
        "namespaces",
        "events",
        "serviceaccounts",
      ]
    verbs: ["get", "list", "watch", "create", "patch","update"]